// import { Inter } from 'next/font/google'
import "./globals.css";
import Navbar from "./Components/Navbar";
import LeftSideBar from "./Components/LeftSideBar";
// 'use-client'
// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html>
      <div className="flex gap-4 px-4 mt-10">
        
          <LeftSideBar></LeftSideBar>
       
        <div>
          <Navbar></Navbar>
          {children}
        </div>
      </div>
    </html>
  );
};

export default RootLayout;
